DROP TABLE t_vb_biotipo CASCADE CONSTRAINTS;

DROP TABLE t_vb_cliente CASCADE CONSTRAINTS;

DROP TABLE t_vb_dieta CASCADE CONSTRAINTS;

DROP TABLE t_vb_exerc CASCADE CONSTRAINTS;

DROP TABLE t_vb_medida CASCADE CONSTRAINTS;

DROP TABLE t_vb_objetivo CASCADE CONSTRAINTS;

DROP TABLE t_vb_tp_treino CASCADE CONSTRAINTS;

DROP TABLE t_vb_treino CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE