SELECT NM_CLIENTE, IDADE_CLIENTE
FROM T_VB_CLIENTE
WHERE GENERO_CLIENTE = 'Feminino'
ORDER BY IDADE_CLIENTE DESC;


SELECT C.NM_CLIENTE, B.NM_BIOTIPO
FROM T_VB_CLIENTE C
INNER JOIN T_VB_BIOTIPO B ON C.ID_BIOTIPO = B.ID_BIOTIPO
WHERE C.IDADE_CLIENTE >= 25;


SELECT ID_OBJETIVO, COUNT(*) AS TOTAL_DE_CLIENTES
FROM T_VB_CLIENTE
GROUP BY ID_OBJETIVO
ORDER BY TOTAL_DE_CLIENTES DESC;


SELECT O.NM_OBJETIVO, AVG(M.PESO_MEDIDA) AS PESO_MEDIO
FROM T_VB_OBJETIVO O
INNER JOIN T_VB_CLIENTE C ON O.ID_OBJETIVO = C.ID_OBJETIVO
INNER JOIN T_VB_MEDIDAS M ON C.ID_MEDIDA = M.ID_MEDIDA
GROUP BY O.NM_OBJETIVO
HAVING AVG(M.PESO_MEDIDA) > 70
ORDER BY PESO_MEDIO DESC;