

-- SELECT PARA PUXAR O NOME E A IDADE DE TODOS OS CLIENTES QUE POSSUEM GÊNERO "Masculino"
-- SENDO ORDENADO PELA IDADE DO CLIENTE EM ORDEM DECRESCENTE
SELECT  NM_CLIENTE, 
        IDADE_CLIENTE
FROM T_VB_CLIENTE
WHERE GENERO_CLIENTE = 'Masculino'
ORDER BY IDADE_CLIENTE DESC;




-- SELECT COM INNER JOIN, PARA BUSCAR NOME, IDADE E O NOME DO BIOTIPO DE TODOS OS CLIENTES QUE POSSUIREM A IDADE MAIOR OU IGUAL A 10 ANOS
-- SENDO ORDENADO PELA IDADE DO CLIENTE EM ORDEM CRESCENTE
SELECT  C.NM_CLIENTE, 
        C.IDADE_CLIENTE, 
        B.NM_BIOTIPO
FROM T_VB_CLIENTE C
INNER JOIN T_VB_BIOTIPO B ON C.ID_BIOTIPO = B.ID_BIOTIPO
WHERE C.IDADE_CLIENTE >= 10
ORDER BY C.IDADE_CLIENTE ASC;




-- SELECT QUE BUSCA A QUANTIDADE DE CLIENTES QUE POSSUEM O ID DA TABELA OBJETIVO, CONECTADA COM A TABELA CLIENTE
-- SENDO ORDENADA PELO TOTAL DE CLIENTES EM FORMATO DECRESCENTE
SELECT  ID_OBJETIVO, 
        COUNT(*) AS TOTAL_DE_CLIENTES
FROM T_VB_CLIENTE
GROUP BY ID_OBJETIVO
ORDER BY TOTAL_DE_CLIENTES DESC;




-- SELECT PARA PUXAR O NOME DO OBJETIVO E A MÉDIA DE PESO POR CADA OBJETIVO
-- SENDO AGRUPADO PELO NOME DO OBJETIVO E DEPOIS FILTADO COM O COMANDO HAVING
-- PARA QUE A MÉDIA DE PESO SEJA MAIOR QUE 50 QUILOS
-- SENDO ORDENADA DE FORMA DECRESCENTE DE PESO_MEDIO
SELECT  O.NM_OBJETIVO, 
        AVG(M.PESO_MEDIDA) AS PESO_MEDIO
FROM T_VB_OBJETIVO O
INNER JOIN T_VB_CLIENTE C ON O.ID_OBJETIVO = C.ID_OBJETIVO
INNER JOIN T_VB_MEDIDA M ON C.ID_MEDIDA = M.ID_MEDIDA
GROUP BY O.NM_OBJETIVO
HAVING AVG(M.PESO_MEDIDA) > 50
ORDER BY PESO_MEDIO DESC;

